
import { Category, Quota } from './types';

export const DISTRICTS = [
  'All Tamil Nadu',
  'Ariyalur',
  'Chengalpattu',
  'Chennai',
  'Coimbatore',
  'Cuddalore',
  'Dharmapuri',
  'Dindigul',
  'Erode',
  'Kallakurichi',
  'Kanchipuram',
  'Kanyakumari',
  'Karur',
  'Krishnagiri',
  'Madurai',
  'Mayiladuthurai',
  'Nagapattinam',
  'Namakkal',
  'Nilgiris',
  'Perambalur',
  'Pudukkottai',
  'Ramanathapuram',
  'Ranipet',
  'Salem',
  'Sivaganga',
  'Tenkasi',
  'Thanjavur',
  'Theni',
  'Thoothukudi',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupathur',
  'Tiruppur',
  'Tiruvallur',
  'Tiruvannamalai',
  'Tiruvarur',
  'Vellore',
  'Viluppuram',
  'Virudhunagar'
];

export const COURSES = [
  'Computer Science and Engineering (CSE)',
  'Information Technology (IT)',
  'Artificial Intelligence and Data Science (AI&DS)',
  'Computer Science and Engineering (AI and Machine Learning)',
  'Computer Science and Business Systems',
  'Cyber Security',
  'Computer Science and Design',
  'Electronics and Communication Engineering (ECE)',
  'Electrical and Electronics Engineering (EEE)',
  'Mechanical Engineering (MECH)',
  'Civil Engineering (CIVIL)',
  'Electronics and Instrumentation Engineering (EIE)',
  'Instrumentation and Control Engineering (ICE)',
  'Mechatronics Engineering',
  'Robotics and Automation',
  'Aeronautical Engineering',
  'Aerospace Engineering',
  'Automobile Engineering',
  'Biotechnology',
  'Biomedical Engineering',
  'Medical Electronics',
  'Chemical Engineering',
  'Agricultural Engineering',
  'Food Technology',
  'Petrochemical Engineering',
  'Petroleum Engineering',
  'Textile Technology',
  'Fashion Technology',
  'Handloom and Textile Technology',
  'Leather Technology',
  'Industrial Engineering',
  'Manufacturing Engineering',
  'Mining Engineering',
  'Printing Technology',
  'Ceramic Technology',
  'Plastic Technology'
];

export const CATEGORIES = Object.values(Category);
export const QUOTAS = Object.values(Quota);
